trigger: none

resources:
  pipelines:
  - pipeline: ci
    source: DevSquad.RunningRecords.Backend-CI

variables:
- group: DevSquad.RunningRecords.Backend

stages:
- stage: continuous_deployment
  displayName: 'Continuous Deployment'
  jobs:
  
  - deployment: build_validate
    displayName: build image and deploy into k8s
    environment: $(Environment)
    
    pool:
      name: Default
      demands:
      - agent.name -equals ALEJANDRO-OSPINO
    
    strategy:
      runOnce:
        deploy: 
          steps:
              
          - task: Docker@2
            displayName: Docker Build & Push
            inputs:
              containerRegistry: '$(dockerRegistrySC)'
              repository: '$(dockerRepository)'
              command: 'buildAndPush'
              Dockerfile: '../ci/Artifacts/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
          
          - task: HelmDeploy@0
            displayName: "Helm upgrade"
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: '$(kubernetesSC)'
              namespace: '$(kubernetesNamespace)'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.DefaultWorkingDirectory)/../ci/Manifests/running-records-api'
              releaseName: 'running-records-api'
              valueFile: '$(System.DefaultWorkingDirectory)/../ci/Manifests/running-records-api/values.yaml'
              arguments: '--set image.registryName=$(dockerRegistry) --set image.repository=$(dockerRepository) --set image.tag=$(Build.BuildId) --set version=$(Build.BuildId)'
              failOnStderr: true
            
          
