trigger: none

resources:
  pipelines:
  - pipeline: ci
    source: DevSquad.RunningRecords.Backend-CI

variables:
- group: DevSquad.RunningRecords.Backend

stages:
- stage: continuous_deployment
  displayName: 'Continuous Deployment'
  jobs:
  
  - deployment: build_validate
    displayName: build image and deploy into k8s
    environment: $(Environment)
    
    pool:
      name: Default
      demands:
      - agent.name -equals ALEJANDRO-OSPINO
    
    strategy:
      runOnce:
        deploy: 
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: Download app atrifacts
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'Artifacts'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: Docker@2
            displayName: Construcción y publicación de imágen Api
            inputs:
              containerRegistry: '$(dockerRegistrySC)'
              repository: 'img-$(Build.Repository.Name)-Api'
              command: 'buildAndPush'
              Dockerfile: 'src/DevSquad.RunningRecords.Backend.Api/Dockerfile'
              buildContext: '$(System.DefaultWorkingDirectory)'
              tags: |
                latest
                $(Build.BuildId)
